import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = []
path = [cwd]

if GetDepend(['BSP_USING_TCA9539']):
    src += Glob('tca9539.c')

group = DefineGroup('TCA9539', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
