Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the app files.
src = []

if GetDepend(['RT_USING_SERIAL']):
    if GetDepend(['RT_USING_SERIAL_V2']):
        src += ['test_uart_v2.c']
    else:
        src += ['test_uart_v1.c']

if GetDepend(['RT_USING_SPI']):
    src += ['test_spi.c']

if GetDepend(['RT_USING_QSPI']):
    src += ['test_qspi.c']

if GetDepend(['RT_USING_I2C']):
    src += ['test_i2c.c']
    if GetDepend(['RT_USING_I2C_BITOPS']):
        src += ['solf_i2c_sample.c']

if GetDepend(['BSP_USING_ETH', 'RT_USING_LWIP']):
    src += ['test_eth.c']

if GetDepend(['RT_USING_ADC']):
    src += ['test_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['test_dac.c']

if GetDepend(['RT_USING_CAN']):
    src += ['test_can.c']

if GetDepend(['RT_USING_RTC']):
    src += ['test_rtc.c']

if GetDepend(['RT_USING_WDT']):
    src += ['test_wdt.c']

if GetDepend(['RT_USING_HWTIMER']):
    src += ['test_hwtimer.c']

if GetDepend(['RT_USING_PULSE_ENCODER']):
    src += ['test_pulse_encoder.c']

if GetDepend(['RT_USING_PWM']):
    src += ['test_pwm.c']

if GetDepend(['RT_USING_PM']):
    src += ['test_pm.c']

if GetDepend('RT_USING_HWCRYPTO'):
    src += ['test_crypto.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['drv_sdio.c']

if GetDepend(['BSP_USING_EXMC', 'BSP_USING_SDRAM']):
    src += ['test_sdram.c']

if GetDepend(['BSP_USING_EXMC', 'BSP_USING_NAND']):
    src += ['test_nand.c']

if GetDepend(['BSP_USING_USBD']):
    src += ['test_usbd.c']


path = [cwd]


group = DefineGroup('Tests', src, depend = [''], CPPPATH = path)

Return('group')


